### ISSUE TITLE
Updated dump

### ISSUE THREAD

**Issue by stetamatea** [ajgon/bgtoolset#2]
Hi, the official toolset is down and your dump support up to 4.88 firmware
Someone else seems to have already dumped new version and its being hosted here https://www.pspx.ru/forum/bgtoolset/
Would it be possible to dump this too in case it goes down?
If not, once official toolset is back would you be able to dump latest version?
At this point im just afraid of these online tools being taken down and i would like to have my own private locally hosted instances.

Thanks in advance

**Comment by brownboi2** [comment]
Although the site is in Russian (i think?), I can confirm the site works on 4.89 and runs the patch sucessfully. Hopefully, ajgon ends up dumping it

**Comment by ajgon** [comment]
Reopening, as adding 4.89 would require extra work...
