### ISSUE TITLE
Tested 2 other consoles on 4.86, working

### ISSUE THREAD

**Issue by prochazkaml** [ajgon/bgtoolset#7]
Hi, I'd just like to let you know that with this dump (self hosted on a local machine), I have successfully patched 2 PS3 consoles that are not in the list in the README (CECH-2004B and CECH-L04) on version 4.86 (using a custom nofsm_patch_486.bin file that I have thankfully downloaded earlier back when the official site was still up). 👍

**Comment by ajgon** [comment]
Thank you for info, updated readme :+1:

**Comment by prochazkaml** [comment]
You're welcome!

Yesterday, I also used this with a CECH-3004B on 4.89 (no patching, of course, as this model doesn't even support it) to extract its IDPS, as I wanted to decrypt its system backup. Not sure if that's worth putting in the readme, but it's yet another thing that this tool might useful for :)

**Comment by ajgon** [comment]
Nah, it will create too much confusion - but thanks, good to know :)

**Comment by prochazkaml** [comment]
Alright, just wanted to let you know - it's not a patchable system anyway. 👍
